name: 'Configure CF CLI'
description: 'Installs the latest linux64 binary for the CloudFoundry CLI as outlined here: https://github.com/cloudfoundry/cli/blob/master/doc/installation-instructions/installation-instructions-v7.md#installers-and-compressed-binaries'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p cfcli/bin
        cd cfcli/bin
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx
        echo "$(pwd)" >> $GITHUB_PATH
      shell: bash
